### Step 1. Import the necessary libraries.

In [1]:
import pandas as pd

### Step 2. Import the dataset.

In [2]:
pd.read_csv("7_ecommerce_sales_1000_records - 7_ecommerce_sales_1000_records.csv")

,Order_ID,Product,Category,Quantity,Price,City,Date
0,ORD1001,Backpack,Accessories,1,1629.00,Hyderabad,2026-03-04
1,ORD1002,Keyboard,Electronics,2,1570.94,Surat,2026-01-23
2,ORD1003,Book,Books,4,407.86,Mumbai,2026-02-25
3,ORD1004,Keyboard,Electronics,5,1530.61,Surat,2026-02-20
4,ORD1005,Tablet,Electronics,5,27549.31,Jaipur,2026-05-31
...,...,...,...,...,...,...,...
995,ORD1996,Watch,Accessories,5,4711.82,Ahmedabad,2026-05-22
996,ORD1997,T-Shirt,Fashion,5,861.96,Surat,2026-05-01
997,ORD1998,Backpack,Accessories,2,1751.69,Bangalore,2026-05-31
998,ORD1999,Tablet,Electronics,3,25949.74,Surat,2026-05-11
999,ORD2000,Smartphone,Electronics,4,17509.92,Ahmedabad,2026-06-19


### Step 3. Assign it to a variable called sales.

In [3]:
sales = pd.read_csv("7_ecommerce_sales_1000_records - 7_ecommerce_sales_1000_records.csv")

### Step 4. Display the first 10 rows of the dataset.

In [4]:
sales.head(10)

  Order_ID     Product     Category  Quantity     Price       City        Date
0  ORD1001    Backpack  Accessories         1   1629.00  Hyderabad  2026-03-04
1  ORD1002    Keyboard  Electronics         2   1570.94      Surat  2026-01-23
2  ORD1003        Book        Books         4    407.86     Mumbai  2026-02-25
3  ORD1004    Keyboard  Electronics         5   1530.61      Surat  2026-02-20
4  ORD1005      Tablet  Electronics         5  27549.31     Jaipur  2026-05-31
5  ORD1006     T-Shirt      Fashion         1    840.36      Delhi  2026-06-28
6  ORD1007       Watch  Accessories         3   4776.92  Bangalore  2026-03-28
7  ORD1008  Smartphone  Electronics         1  17567.74       Pune  2026-03-30
8  ORD1009        Book        Books         3    477.64     Jaipur  2026-05-18
9  ORD1010  Smartphone  Electronics         4  16483.68  Hyderabad  2026-06-10


### Step 5. What is the total number of observations (rows) in the dataset?

In [5]:
sales.shape[1]

7

### Step 6. What is the total number of columns in the dataset?

In [6]:
sales.shape[0]

1000

### Step 7. Print the names of all the columns.

In [7]:
sales.columns

Index(['Order_ID', 'Product', 'Category', 'Quantity', 'Price', 'City', 'Date'], dtype='str')

### Step 8. How is the dataset indexed?

In [8]:
sales.index

RangeIndex(start=0, stop=1000, step=1)

### Step 9. Display the data types of all columns.

In [9]:
sales.dtypes

Order_ID        str
Product         str
Category        str
Quantity      int64
Price       float64
City            str
Date            str
dtype: object

### Step 10. Check if there are any missing values in the dataset.

In [10]:
sales.isnull().sum()

Order_ID    0
Product     0
Category    0
Quantity    0
Price       0
City        0
Date        0
dtype: int64

### Step 11. How many unique products are available?

In [11]:
sales['Product'].nunique()

14

### Step 12. Which product was sold the most (based on total quantity)?

In [12]:
sales.groupby('Product')['Quantity'].sum().idxmax()

'T-Shirt'

### Step 13. How many units of the most sold product were purchased?

In [13]:
sales.groupby('Product')['Quantity'].sum().max()

np.int64(259)

### Step 14. Which category generated the highest total sales revenue?

In [14]:
sales.groupby('Category')['Price'].sum().idxmax()

'Electronics'

### Step 15. Which city placed the highest number of orders?

In [15]:
sales.groupby('City')['Quantity'].sum().idxmax()

'Mumbai'

### Step 16. What is the total quantity of products sold?

### Step 17. Calculate the total revenue of the dataset.

### Step 18. What is the average order value?

### Step 19. Which product generated the highest revenue?

### Step 20. Which city generated the highest total revenue?

### Step 21. On which date was the maximum revenue generated?

### Step 22. Which category has the highest average product price?

### Step 23. Find the top 10 best-selling products based on quantity sold.

### Step 24. Find the top 5 cities by total revenue.

### Step 25. Which product has the highest average selling price?

### Step 26. What is the average quantity purchased per order?

### Step 27. How many orders were placed in each category?

### Step 28. Find the total revenue generated by each category.


### Step 29. Sort the dataset by Price in descending order and display the top 10 records.

### Step 30. Create a new column called Revenue = Quantity × Price and display the first 10 rows.